import { useEffect, useState } from 'react'
import { ArrowLeft, Eye, EyeOff, KeyRound, LockKeyhole, ShieldCheck } from 'lucide-react'
import { Link, useNavigate } from 'react-router-dom'
import { useApp } from '@/contexts/AppContext'
import { Button, Card } from '@/components/ui'

export default function AdminLoginPage() {
  const { adminAuthenticated, adminLogin, notify } = useApp()
  const navigate = useNavigate()
  const [email, setEmail] = useState('admin@admin.com')
  const [password, setPassword] = useState('123456')
  const [showPassword, setShowPassword] = useState(false)
  const [error, setError] = useState('')
  useEffect(() => { if (adminAuthenticated) navigate('/admin', { replace: true }) }, [adminAuthenticated, navigate])
  const submit = (event: React.FormEvent) => { event.preventDefault(); if (!adminLogin(email, password)) { setError('Acesso negado. Use o e-mail administrativo e a senha cadastrada.'); return }; setError(''); notify({ title: 'Acesso administrativo liberado', message: 'A central administrativa está disponível.', tone: 'success' }); navigate('/admin') }
  return <div className="flex min-h-screen items-center justify-center bg-navy p-5"><Card className="w-full max-w-md animate-page-in p-6 sm:p-8"><Link to="/login" className="mb-8 inline-flex items-center gap-2 text-sm font-bold text-slate-500 transition hover:-translate-x-1 hover:text-teal"><ArrowLeft size={16} /> Voltar ao portal</Link><div className="mb-8"><div className="mb-5 flex h-14 w-14 items-center justify-center rounded-2xl bg-navy text-white"><ShieldCheck size={27} /></div><p className="mb-2 text-xs font-bold uppercase tracking-[0.2em] text-teal">Área restrita</p><h1 className="font-display text-3xl font-black tracking-tight text-ink dark:text-white">Login administrativo</h1><p className="mt-2 text-sm leading-6 text-slate-500 dark:text-slate-300">Esta entrada é exclusiva para a conta administrativa do sistema.</p></div><form onSubmit={submit} className="space-y-5"><label className="block"><span className="mb-2 block text-sm font-bold text-ink dark:text-white">E-mail do administrador</span><input required type="email" value={email} onChange={(event) => setEmail(event.target.value)} className="w-full rounded-xl border border-line bg-white px-4 py-3 text-sm outline-none transition focus:border-teal focus:ring-4 focus:ring-teal/10 dark:border-white/10 dark:bg-white/5 dark:text-white" /></label><label className="block"><span className="mb-2 block text-sm font-bold text-ink dark:text-white">Senha administrativa</span><div className="relative"><LockKeyhole size={17} className="absolute left-3.5 top-1/2 -translate-y-1/2 text-slate-400" /><input required type={showPassword ? 'text' : 'password'} value={password} onChange={(event) => setPassword(event.target.value)} className="w-full rounded-xl border border-line bg-white px-4 py-3 pl-11 pr-11 text-sm outline-none transition focus:border-teal focus:ring-4 focus:ring-teal/10 dark:border-white/10 dark:bg-white/5 dark:text-white" /><button type="button" onClick={() => setShowPassword((value) => !value)} className="absolute right-3.5 top-1/2 -translate-y-1/2 text-slate-400" aria-label={showPassword ? 'Ocultar senha' : 'Mostrar senha'}>{showPassword ? <EyeOff size={17} /> : <Eye size={17} />}</button></div></label>{error && <p role="alert" className="rounded-xl bg-rose-50 px-3 py-2.5 text-xs font-semibold text-rose-700 dark:bg-rose-950/30 dark:text-rose-300">{error}</p>}<Button type="submit" size="lg" className="w-full"><KeyRound size={17} /> Entrar na administração</Button></form><div className="mt-7 rounded-2xl border border-dashed border-line bg-cream p-4 text-xs leading-5 text-slate-500 dark:border-white/10 dark:bg-white/5 dark:text-slate-300"><strong className="text-ink dark:text-white">Demonstração:</strong> admin@admin.com · 123456<br />Em produção, substitua esta credencial por autenticação segura no backend.</div></Card></div>
}
