import { useState } from 'react'
import { ArrowLeft, CheckCircle2, KeyRound, Mail, ShieldCheck } from 'lucide-react'
import { Link } from 'react-router-dom'
import { Button, Card } from '@/components/ui'

export default function ForgotPasswordPage() {
  const [email, setEmail] = useState('')
  const [sent, setSent] = useState(false)
  const [error, setError] = useState('')
  const submit = (event: React.FormEvent) => { event.preventDefault(); if (!email.includes('@')) { setError('Informe um e-mail válido para continuar.'); return }; setError(''); setSent(true) }
  return <div className="flex min-h-screen items-center justify-center bg-cream p-5 dark:bg-[#0b1f2d]"><Card className="w-full max-w-md animate-page-in p-6 sm:p-8"><Link to="/login" className="mb-8 inline-flex items-center gap-2 text-sm font-bold text-slate-500 transition hover:-translate-x-1 hover:text-teal"><ArrowLeft size={16} /> Voltar para o login</Link>{sent ? <div className="text-center"><div className="mx-auto flex h-16 w-16 items-center justify-center rounded-3xl bg-emerald-50 text-emerald-600 dark:bg-emerald-950/30 dark:text-emerald-300"><CheckCircle2 size={30} /></div><h1 className="mt-6 font-display text-2xl font-black text-ink dark:text-white">Solicitação recebida</h1><p className="mt-3 text-sm leading-6 text-slate-500 dark:text-slate-300">Se o e-mail estiver cadastrado, enviaremos as instruções para redefinir sua senha. Nesta demonstração, nenhum e-mail real é enviado.</p><Link to="/login" className="mt-6 inline-flex"><Button>Voltar ao login</Button></Link></div> : <><div className="mb-8"><div className="mb-5 flex h-14 w-14 items-center justify-center rounded-2xl bg-teal/10 text-teal"><KeyRound size={25} /></div><p className="mb-2 text-xs font-bold uppercase tracking-[0.2em] text-teal">Recuperação de acesso</p><h1 className="font-display text-3xl font-black tracking-tight text-ink dark:text-white">Esqueci minha senha</h1><p className="mt-2 text-sm leading-6 text-slate-500 dark:text-slate-300">Informe seu e-mail institucional para receber as instruções de recuperação.</p></div><form onSubmit={submit} className="space-y-5"><label className="block"><span className="mb-2 block text-sm font-bold text-ink dark:text-white">E-mail institucional</span><div className="relative"><Mail size={17} className="absolute left-3.5 top-1/2 -translate-y-1/2 text-slate-400" /><input autoFocus required type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="seu@email.com" className="w-full rounded-xl border border-line bg-white px-4 py-3 pl-11 text-sm outline-none transition focus:border-teal focus:ring-4 focus:ring-teal/10 dark:border-white/10 dark:bg-white/5 dark:text-white" /></div></label>{error && <p role="alert" className="rounded-xl bg-rose-50 px-3 py-2.5 text-xs font-semibold text-rose-700 dark:bg-rose-950/30 dark:text-rose-300">{error}</p>}<Button type="submit" size="lg" className="w-full">Enviar instruções</Button></form><div className="mt-7 flex items-start gap-3 rounded-2xl bg-cream p-4 dark:bg-white/5"><ShieldCheck size={17} className="mt-0.5 shrink-0 text-teal" /><p className="text-xs leading-5 text-slate-500 dark:text-slate-300">A recuperação real deverá ser feita pelo backend com token de uso único e expiração.</p></div></>}</Card></div>
}
