import { useState } from 'react'
import { Accessibility, Captions, Eye, Hand, Keyboard, MonitorSpeaker, Volume2, X } from 'lucide-react'
import { useApp } from '@/contexts/AppContext'
import { Button, cn } from '@/components/ui'

export function AccessibilityWidget() {
  const { accessibility, setAccessibility, announce, notify } = useApp()
  const [open, setOpen] = useState(false)
  const toggle = (key: keyof typeof accessibility) => setAccessibility({ [key]: !accessibility[key] })
  const speak = () => { announce('O painel de acessibilidade está aberto. Use Tab para navegar entre as opções.'); notify({ title: 'Leitura ativada', message: 'O navegador fará a leitura dos avisos importantes.', tone: 'info' }) }
  return <div className="fixed bottom-5 left-5 z-[55]"><Button aria-label="Abrir opções de acessibilidade" onClick={() => setOpen((current) => !current)} className="h-12 w-12 rounded-full bg-teal p-0 text-white shadow-2xl transition hover:scale-110 hover:bg-[#168d83] focus:ring-4 focus:ring-teal/40"><Accessibility size={23} /></Button>{open && <div role="dialog" aria-label="Opções de acessibilidade" className="absolute bottom-16 left-0 w-[min(350px,calc(100vw-2rem))] animate-slide-up rounded-3xl border border-line bg-white p-5 shadow-2xl dark:border-white/10 dark:bg-[#132a3b]"><div className="mb-4 flex items-start justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-[0.2em] text-teal">Plugin assistivo</p><h2 className="mt-1 font-display text-lg font-black text-ink dark:text-white">Acesso para todos</h2><p className="mt-1 text-xs leading-5 text-slate-500 dark:text-slate-300">Preferências ficam salvas neste dispositivo.</p></div><button onClick={() => setOpen(false)} aria-label="Fechar opções de acessibilidade" className="rounded-xl p-2 text-slate-400 hover:bg-cream dark:hover:bg-white/10"><X size={17} /></button></div><div className="space-y-2"><AccessToggle icon={Eye} label="Baixa visão e cegueira" detail="Alto contraste, foco ampliado e leitura" active={accessibility.screenReader} onClick={() => toggle('screenReader')} /><AccessToggle icon={Captions} label="Surdez" detail="Alertas visuais e legendas preparadas" active={accessibility.visualAlerts} onClick={() => toggle('visualAlerts')} /><AccessToggle icon={Hand} label="Comunicação sem fala" detail="Contato por texto e atalhos visuais" active={accessibility.textCommunication} onClick={() => toggle('textCommunication')} /><AccessToggle icon={Keyboard} label="Navegação por teclado" detail="Foco visível em todos os controles" active={accessibility.keyboardNavigation} onClick={() => toggle('keyboardNavigation')} /></div><div className="mt-4 grid gap-2 sm:grid-cols-2"><Button size="sm" variant="secondary" onClick={speak}><Volume2 size={15} /> Ler instruções</Button><Button size="sm" variant="secondary" onClick={() => { setAccessibility({ visualAlerts: true, textCommunication: true, keyboardNavigation: true, screenReader: true }); announce('Todas as ferramentas de acessibilidade foram ativadas.'); notify({ title: 'Acessibilidade ativada', message: 'Recursos assistivos visuais, textuais e de teclado estão ativos.', tone: 'success' }) }}><MonitorSpeaker size={15} /> Ativar tudo</Button></div></div>}</div>
}

function AccessToggle({ icon: Icon, label, detail, active, onClick }: { icon: typeof Eye; label: string; detail: string; active: boolean; onClick: () => void }) { return <button onClick={onClick} aria-pressed={active} className={cn('flex w-full items-center gap-3 rounded-2xl border p-3 text-left transition hover:-translate-y-0.5', active ? 'border-teal bg-teal/5 dark:bg-teal/10' : 'border-line/70 dark:border-white/10')}><span className={cn('flex h-9 w-9 shrink-0 items-center justify-center rounded-xl', active ? 'bg-teal text-white' : 'bg-cream text-slate-400 dark:bg-white/5')}><Icon size={17} /></span><span className="min-w-0 flex-1"><strong className="block text-xs font-bold text-ink dark:text-white">{label}</strong><small className="mt-0.5 block text-[10px] leading-4 text-slate-400">{detail}</small></span><span className={cn('h-5 w-9 rounded-full p-1 transition', active ? 'bg-teal' : 'bg-slate-200 dark:bg-white/10')}><span className={cn('block h-3 w-3 rounded-full bg-white transition', active ? 'ml-4' : 'ml-0')} /></span></button> }
