import { useState } from 'react'
import { Users } from 'lucide-react'
import { schoolClasses, students } from '@/data/mocks'
import { Badge, Button, Card, EmptyState, Modal, Avatar } from '@/components/ui'

export default function ClassStudentsCards() {
  const [selected, setSelected] = useState<string | null>(null)
  const list = students.filter((student) => student.className === selected)
  return <><div className="mb-6 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{schoolClasses.map((schoolClass) => <Card key={schoolClass.id} className="p-5 transition hover:-translate-y-0.5 hover:border-teal/40"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-wider text-teal">Cartão da turma</p><h2 className="mt-1 font-display text-xl font-black text-ink dark:text-white">{schoolClass.name}</h2><p className="mt-1 text-xs text-slate-500 dark:text-slate-300">{schoolClass.grade} · {schoolClass.shift}</p></div><Badge tone="success">{schoolClass.status}</Badge></div><div className="mt-4 grid grid-cols-2 gap-3 rounded-xl bg-cream p-3 dark:bg-white/5"><div><p className="text-[10px] uppercase text-slate-400">Alunos</p><p className="mt-1 text-lg font-black text-ink dark:text-white">{schoolClass.students}</p></div><div><p className="text-[10px] uppercase text-slate-400">Frequência</p><p className="mt-1 text-lg font-black text-teal">{schoolClass.attendance}%</p></div></div><Button size="sm" className="mt-4 w-full" onClick={() => setSelected(schoolClass.name)}><Users size={14} /> Mostrar lista de alunos</Button></Card>)}</div><Modal open={selected !== null} onClose={() => setSelected(null)} title={`Alunos da turma ${selected || ''}`} description="Lista filtrada pela turma selecionada."><div className="space-y-2">{list.map((student) => <div key={student.id} className="flex items-center gap-3 rounded-xl border border-line/70 p-3 dark:border-white/10"><Avatar initials={student.initials} /><div className="min-w-0 flex-1"><p className="text-sm font-bold text-ink dark:text-white">{student.name}</p><p className="text-xs text-slate-400">{student.registration} · média {student.average.toFixed(1)} · frequência {student.attendance}%</p></div><Badge tone={student.status === 'Atenção' ? 'warning' : 'success'}>{student.status}</Badge></div>)}{selected && list.length === 0 && <EmptyState title="Nenhum aluno demonstrativo" description="A turma está pronta para receber alunos quando a API estiver conectada." />}</div></Modal></>
}
